### ISSUE TITLE
Backup the database

### ISSUE THREAD

**Issue by stakach** [PlaceOS/init#7]
Would it be possible to run a database backup from this container?
Or should we do it from the database containers?

https://rethinkdb.com/docs/backup/

Basically thinking we run a backup and then upload the output to an S3 bucket
ping @w-le what do you think?

**Comment by caspiano** [comment]
I believe using a task to backup is a good idea.
[We can use a cron](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to trigger the execution of the sam task via the container.

Otherwise, we could have an init container with an overide of the entry and a cron of the backup task if we're still using pure container deploys.

Probably good to keep the logic out of the DB to simplify using PaaS RethinkDB.

**Comment by caspiano** [comment]
If we had an cloud volume mounted, we could run the backups via a cron on the DB container? @stakach

**Comment by stakach** [comment]
Yeah we do have a volume mounted. So the backup could occur on the DB container

@w-le you wrote a script for couchbase that uploads backups to S3 right?
Would love your opinion on how we do this

**Comment by w-le** [comment]
So that very very old method I used for backing up couch to s3 was just utilising an existing seperate docker image from a systemD unit+timer
https://bitbucket.org/aca/deprecated-server-setup/src/master/units/aca-s3backup.service
https://github.com/istepanov/docker-backup-to-s3

For our cloud native deployments, we can simply utilise volume snapshots. This simplifies the backup and restore process (no rare rethink specific knowledge - only common cloud admin knowledge) and offloads the onus of this management onto the cloud admin instead.
An added benefit is that these snapshots save rethink cluster config data, while `rethink dump` does not.

For non-cloud deployments (hopefully some time before we have to do one in production), I'd recommend that enterprise clients snapshot the whole DB VM's disk (they tend to do this anyway) and use that for restore. This again abstracts the processes to something admins are already familiar with and excludes PlaceOS involvement.

In non-cloud scenarios where the above is not suitable or desired (hopefully not many), we can use method similar to the aforementioned:
- a cron on the VM triggers...
- a `docker run` of a purpose-built container (e.g. "rethink-backup")
- the container runs `rethink dump` and then uploads the tar.gz to an s3 / azure BLOB / gcp BLOB location
Note that unlike couch's cbbackup, `rethink dump` doesn't have incremental (diff) backups at this stage. 
Note that with this method, the management of the backups and execution of restores will be work for PlaceOS

**Comment by stakach** [comment]
nice, we could probably run a periodic `rethink dump` too just in case.
but then backing up the volume via a snapshot is a great idea.

**Comment by caspiano** [comment]
resolved in #14
